
server.port=8082
spring.application.name=aulajovem2026IA

spring.datasource.url=jdbc:postgresql://localhost:5432/eventspace
spring.datasource.username=postgres
spring.datasource.password=210382
spring.datasource.driver-class-name=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.HSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
